/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-11-26 12:32:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/admin/footer.jsp", Long.valueOf(1700216585933L));
    _jspx_dependants.put("/admin/header.jsp", Long.valueOf(1701001906384L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\" xmlns:jsp=\"\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Admin Dashboard - Bookstore</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/admin.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Book Store</title>\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/header.css\" rel=\"stylesheet\"> <!-- Link your CSS file -->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header class=\"main-header\">\r\n");
      out.write("    <div class=\"header-content\">\r\n");
      out.write("            <div class=\"logo\">\r\n");
      out.write("                <img alt=\"Book Store Logo\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/image/logo.jpeg\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"search-bar\">\r\n");
      out.write("                <input placeholder=\"Search books...\" type=\"text\">\r\n");
      out.write("                <button type=\"submit\">Search</button>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"right-column\">\r\n");
      out.write("            <div class=\"user-actions\" >\r\n");
      out.write("                <a href=\"signin.html\">Sign In</a>\r\n");
      out.write("                <a href=\"register.html\">Register</a>\r\n");
      out.write("                <a href=\"cart.html\">Cart</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <nav class=\"categories\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li><a href=\"#dashboard\">Dashboard</a></li>\r\n");
      out.write("            <li><a href=\"#book-management\">Book Management</a></li>\r\n");
      out.write("            <li><a href=\"#order-management\">Order Management</a></li>\r\n");
      out.write("            <li><a href=\"#user-management\">User Management</a></li>\r\n");
      out.write("            <!-- Additional navigation items -->\r\n");
      out.write("        </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("    <h1>Admin Dashboard</h1>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<main>\r\n");
      out.write("    <!-- Dashboard Overview Section -->\r\n");
      out.write("    <section id=\"dashboard\">\r\n");
      out.write("        <h2>Dashboard Overview</h2>\r\n");
      out.write("        <!-- Content for dashboard metrics, charts, etc. -->\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- Book Management Section -->\r\n");
      out.write("    <section id=\"book-management\">\r\n");
      out.write("        <h2>Book Management</h2>\r\n");
      out.write("        <!-- Content for managing books -->\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- Order Management Section -->\r\n");
      out.write("    <section id=\"order-management\">\r\n");
      out.write("        <h2>Order Management</h2>\r\n");
      out.write("        <!-- Content for managing orders -->\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- User Management Section -->\r\n");
      out.write("    <section id=\"user-management\">\r\n");
      out.write("        <h2>User Management</h2>\r\n");
      out.write("        <!-- Content for managing users -->\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Other sections for reports, settings, etc. -->\r\n");
      out.write("</main>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Book Store</title>\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/footer.css\" rel=\"stylesheet\"> <!-- Link your CSS file -->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<footer class=\"main-footer\">\r\n");
      out.write("    <div class=\"footer-content\">\r\n");
      out.write("        <div class=\"footer-column\">\r\n");
      out.write("            <h3>About Us</h3>\r\n");
      out.write("            <p>Information about the bookstore and its mission.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"footer-column\">\r\n");
      out.write("            <h3>Contact Us</h3>\r\n");
      out.write("            <p>Email: info@bookstore.com<br>Phone: +1234567890</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"footer-column\">\r\n");
      out.write("            <h3>Follow Us</h3>\r\n");
      out.write("            <p>Links to social media profiles.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
